# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_auto_20170504_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='analyzers',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('flake8', 'flake8')], max_length=6, verbose_name='analyzers'),
        ),
        migrations.AlterField(
            model_name='project',
            name='last_analyzed',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Last analyzed'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.CharField(max_length=200, unique=True, verbose_name='Url'),
        ),
    ]
