# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 11:07
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0005_project_running'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name'),
            preserve_default=False,
        ),
    ]
