# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 09:39
from __future__ import unicode_literals

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0008_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='analyzers',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('flake8', 'flake8'), ('pylint', 'pylint')], max_length=13, verbose_name='analyzers'),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.CharField(max_length=200, unique=True, verbose_name='Url of the repository'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.Project', verbose_name='Project'),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=set([('email', 'project')]),
        ),
    ]
