# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
                ('last_checked', models.DateTimeField(blank=True, default=None)),
                ('analyzers', multiselectfield.db.fields.MultiSelectField(choices=[('flake8', 'flake8')], max_length=6)),
            ],
        ),
    ]
